### ISSUE TITLE
P站上号,开冲！

### ISSUE THREAD

**Issue by ikun194** [heygsc/xiaoheihe-literature#10]
![a5c1a05b4eb6529da626766f70c43c5ded0c0b7bdfe028606df3374240c84821](https://github.com/heygsc/xiaoheihe-literature/assets/129394230/8c39b07c-80a4-42bc-acb9-17fd936e0292)
![d528fbb24534cad426d4ac03b0d1a773194cf73a4781f33320656035988394ed](https://github.com/heygsc/xiaoheihe-literature/assets/129394230/30caf2ca-5f45-4740-9cff-f2f5819178d0)
![d951cd73a139e62a3a773d055123b0ba7d7ed9ac0d10ffc8134548204c58dc5c](https://github.com/heygsc/xiaoheihe-literature/assets/129394230/7807661f-b31e-47df-b412-cfb52399da30)
![eabc999c371bfe4711411c10afee6ddd45e86eba30a047d60aa58bc3f470b0be](https://github.com/heygsc/xiaoheihe-literature/assets/129394230/5957ffab-0f50-426b-ac9e-5fa7104794a8)
![0c5657d570a88b1dd9c99ee6087cafaa1c65a841ed8f0abf9b532fa04cb30bd9](https://github.com/heygsc/xiaoheihe-literature/assets/129394230/0a2293f3-5ee8-43fe-a54e-010bbab36884)
![05d515d3ad540b76cbcc889d058b53860dfd0f9e29bb1a0b3f10e039555894d6](https://github.com/heygsc/xiaoheihe-literature/assets/129394230/e191edd4-df46-40bc-9ff3-54a7a67846ef)
![43b598974547bac3a021b3093570c33c5953371ae6a7b68dfb6ce1d3e97bed92](https://github.com/heygsc/xiaoheihe-literature/assets/129394230/3a07baa0-508f-45d2-ab0c-4154c7dfe2d8)

**Comment by heygsc** [comment]
这个已经收录过了

https://github.com/heygsc/xiaoheihe-literature/blob/main/%E9%BB%91%E7%9B%92%E5%9C%A3%E7%BB%8F/%E7%BB%8F%E5%85%B8/%E7%BB%8F%E5%85%B82/p%E7%AB%99.md
