### ISSUE TITLE
建议：可以在文件的 commit 中添加原帖子链接

### ISSUE THREAD

**Issue by QingchenWait** [heygsc/xiaoheihe-literature#2]
如果原帖的链接还可以访问，可以在提交图片时，在 commit 栏中添加原帖子链接。
在接受投稿时，也可以注明希望投稿者提供链接。
黑盒支持外链生成与访问，最好能利用起来 :)

**Comment by heygsc** [comment]
ok，感谢建议，已经作为投稿的注意事项更新到readme里
