### ISSUE TITLE
Vuepress生成静态站点

### ISSUE THREAD

**Issue by Tohrusky** [heygsc/xiaoheihe-literature#4]
可以考虑vuepress这类静态站点生成工具，cloudflare pages/ github pages+自定义域名托管，更方便盒友欣赏🙇🙇🙇

**Comment by heygsc** [comment]
可以考虑，不过如果不买服务器的话，那种会不会访问的很慢呀。   做站点这件事，目前如果有朋友有想法的话，欢迎pr吧

**Comment by heygsc** [comment]
hhh这个目前真心不太了解，只能说欢迎pr吧
