### ISSUE TITLE
A NEW CASE：分手后你会哭吗？

### ISSUE THREAD

**Issue by RHSNOW** [heygsc/xiaoheihe-literature#8]
圣经发帖时间：2023/6/9 14：42
链接：[旅游三天后，她和我提分手了](https://api.xiaoheihe.cn/v3/bbs/app/api/web/share?link_id=105292961)
文字描述：旅游三天后，女方因男方不成熟等原因提分手。男方力求面谈，且要求不吃火锅。答应后追问道：分手后你会哭吗？
截图：
![image](https://github.com/heygsc/xiaoheihe-literature/assets/30542618/d90acadc-3bc4-4ea9-9f9e-2a89497d70c2)

**Comment by heygsc** [comment]
ok，感谢投稿，已经更新到2023年6月
