### ISSUE TITLE
去哪里刷的star

### ISSUE THREAD

**Issue by mhpsy** [heygsc/xiaoheihe-literature#9]
去哪里刷的star

**Comment by mhpsy** [comment]
> @mhpsy 一颗star没刷过，只能说你不懂这个仓库

抱歉 我无意诋毁 对不起 我的错 我刚刚仔细看了看 确实是很有趣的仓库 我看完了每一张图片

**Comment by heygsc** [comment]
> > @mhpsy 一颗star没刷过，只能说你不懂这个仓库
> 
> 抱歉 我无意诋毁 对不起 我的错 我刚刚仔细看了看 确实是很有趣的仓库 我看完了每一张图片

哈哈哈，没事，欢迎来玩
